import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { DocsSearch } from "@/app/components/DocsSearch";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";
import { isLocale, localized } from "@/lib/i18n";
import { localizedMetadata, SITE_ORIGIN } from "@/lib/metadata";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  return localizedMetadata({
    locale,
    path: "/docs",
    title: locale === "pt-br" ? "Documentação | Open Economics" : "Documentation | Open Economics",
    description: locale === "pt-br" ? "Início rápido, modelo de dados, semântica de datas, revisões e exemplos da Open Economics." : "Quickstart, data model, date semantics, revisions, and examples for Open Economics.",
  });
}
export default async function DocsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params; if (!isLocale(value)) notFound(); const locale = value; const pt = locale === "pt-br";
  return <main className="atlas-page atlas-utility"><SiteHeader locale={locale} /><section className="atlas-docs-head"><div className="atlas-shell"><p className="atlas-kicker">05 / {pt ? "Documentação" : "Documentation"}</p><h1>{pt ? "Contratos claros. Dados legíveis." : "Clear contracts. Readable data."}</h1><p>{pt ? "Resolva uma necessidade econômica e recupere o dado oficial sem perder seu significado." : "Resolve an economic need and retrieve official data without losing its meaning."}</p><DocsSearch locale={locale} /></div></section><div className="atlas-docs-layout atlas-shell"><aside className="atlas-docs-nav"><strong>{pt ? "Guia" : "Guide"}</strong><a href="#quickstart">{pt ? "Descoberta semântica" : "Semantic discovery"}</a><a href={localized(locale, "/guides")}>{pt ? "Exemplos práticos" : "Practical examples"}</a><a href="#model">{pt ? "Modelo de dados" : "Data model"}</a><a href="#dates">{pt ? "Datas e períodos" : "Dates & periods"}</a><a href="#revisions">{pt ? "Revisões" : "Revisions"}</a><strong>{pt ? "Referência" : "Reference"}</strong><a href={localized(locale, "/docs/api-reference")}>{pt ? "Referência da API" : "API reference"}</a><a href={localized(locale, "/docs/errors")}>{pt ? "Erros" : "Errors"}</a><a href={localized(locale, "/docs/attribution")}>{pt ? "Atribuição" : "Attribution"}</a></aside><article className="atlas-docs-content">
    <section id="quickstart"><p className="atlas-kicker">01 / {pt ? "Comece pela necessidade" : "Start with the need"}</p><h2>{pt ? "Descoberta antes do identificador" : "Discovery before identifiers"}</h2><p>{pt ? "A v2 aceita uma necessidade em linguagem natural, resolve o conceito econômico e só então apresenta conjuntos oficiais. Quando não há cobertura, a resposta diz isso explicitamente." : "v2 accepts a natural-language need, resolves the economic concept, and only then presents official datasets. When coverage is missing, the response says so explicitly."}</p><h3>1. {pt ? "Resolva a necessidade" : "Resolve the need"}</h3><pre><code>curl --fail --silent &quot;{SITE_ORIGIN}/api/v2/search?q=desemprego%20desde%202015&quot;</code></pre><h3>2. {pt ? "Inspecione o esquema oficial" : "Inspect the official schema"}</h3><pre><code>curl --fail --silent &quot;{SITE_ORIGIN}/api/v2/datasets/ibge-aggregates%3A6381/schema&quot;</code></pre><p>{pt ? "Os 32 IDs da v1 continuam estáveis; a v2 reúne 12.886 conjuntos oficiais pesquisáveis, seleção multidimensional explícita e acesso direto a dados fiscais nacionais e subnacionais, dívida pública federal, comércio exterior, preços de combustíveis, consumo de eletricidade, emprego formal e fundos de investimento." : "The 32 v1 IDs remain stable; v2 brings together 12,886 searchable official datasets, explicit multidimensional selection, and direct access to national and subnational fiscal, Federal Public Debt, foreign-trade, fuel-price, electricity-consumption, formal-employment, and investment-fund data."}</p><a className="atlas-button primary" href="/api/v2/openapi.json">OpenAPI v2<span>↗</span></a> <a className="atlas-button" href="/api/v1/openapi.json">OpenAPI v1<span>↗</span></a></section>
    <section id="model"><p className="atlas-kicker">02 / {pt ? "Núcleo compartilhado" : "Shared core"}</p><h2>{pt ? "Conceito, conjunto, dimensão e observação" : "Concept, dataset, dimension, and observation"}</h2><p>{pt ? "O conceito descreve o que a pessoa precisa, independentemente da cobertura. O conjunto mantém a identidade oficial. Medidas, classificações e geografias preservam a estrutura antes de chegar às observações." : "The concept describes what a person needs independently of coverage. The dataset preserves official identity. Measures, classifications, and geographies preserve structure before observations are returned."}</p><div className="atlas-schema"><div><code>concept</code><span>{pt ? "Necessidade econômica resolvida" : "Resolved economic need"}</span></div><div><code>dataset</code><span>{pt ? "Identidade e publicador oficiais" : "Official identity and publisher"}</span></div><div><code>dimensions</code><span>{pt ? "Recortes selecionados explicitamente" : "Explicitly selected breakdowns"}</span></div><div><code>period</code><span>{pt ? "Período de referência original" : "Original reference period"}</span></div><div><code>raw_value</code><span>{pt ? "Valor literal da fonte" : "Exact upstream value"}</span></div><div><code>status</code><span>{pt ? "Zero, sigilo e ausência distintos" : "Zero, suppression, and absence stay distinct"}</span></div></div></section>
    <section id="dates"><p className="atlas-kicker">03 / {pt ? "Semântica" : "Semantics"}</p><h2>{pt ? "Datas não são apenas rótulos" : "Dates are not just labels"}</h2><ul><li>{pt ? "Datas de requisição usam YYYY-MM-DD e são inclusivas." : "Request dates use YYYY-MM-DD and are inclusive."}</li><li>{pt ? "Séries mensais do BCB usam dia 01 como marcador do mês de referência." : "BCB monthly series use day 01 as a reference-month marker."}</li><li>{pt ? "Chaves de seis dígitos do IBGE são interpretadas pela frequência." : "IBGE six-digit keys are parsed by frequency."}</li><li>{pt ? "Trimestres móveis da PNAD se sobrepõem e não são pontos mensais." : "PNAD moving quarters overlap; they are not monthly points."}</li></ul></section>
    <section id="revisions"><p className="atlas-kicker">04 / {pt ? "Política de revisões" : "Revision policy"}</p><h2>{pt ? "A história oficial pode mudar" : "Official history can change"}</h2><p>{pt ? "PIB, ajustes sazonais e outras séries podem ser revisados. O histórico é atualizado por upsert; respostas antigas não são tratadas como imutáveis." : "GDP, seasonal adjustments, and other series can be revised. History is refreshed and upserted rather than treated as append-only."}</p><div className="docs-callout"><strong>stale: true</strong><span>{pt ? "Snapshot válido anterior, marcado com Warning 110." : "A prior valid snapshot, marked with Warning 110."}</span></div></section>
  </article></div><SiteFooter locale={locale} /></main>;
}
