import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { DocsSearch } from "@/app/components/DocsSearch";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";
import { isLocale, localized } from "@/lib/i18n";
import { localizedMetadata, SITE_ORIGIN } from "@/lib/metadata";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  return localizedMetadata({
    locale,
    path: "/docs",
    title: locale === "pt-br" ? "Documentação | Open Economics" : "Documentation | Open Economics",
    description: locale === "pt-br" ? "Início rápido, modelo de dados, semântica de datas, revisões e exemplos da Open Economics." : "Quickstart, data model, date semantics, revisions, and examples for Open Economics.",
  });
}
export default async function DocsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params; if (!isLocale(value)) notFound(); const locale = value; const pt = locale === "pt-br";
  return <main className="atlas-page atlas-utility"><SiteHeader locale={locale} /><section className="atlas-docs-head"><div className="atlas-shell"><p className="atlas-kicker">05 / {pt ? "Documentação" : "Documentation"}</p><h1>{pt ? "Contratos claros. Dados legíveis." : "Clear contracts. Readable data."}</h1><p>{pt ? "Tudo para recuperar séries oficiais sem perder seu significado." : "Everything needed to retrieve official series without losing their meaning."}</p><DocsSearch locale={locale} /></div></section><div className="atlas-docs-layout atlas-shell"><aside className="atlas-docs-nav"><strong>{pt ? "Guia" : "Guide"}</strong><a href="#quickstart">{pt ? "Início rápido" : "Quickstart"}</a><a href={localized(locale, "/guides")}>{pt ? "Exemplos práticos" : "Practical examples"}</a><a href="#model">{pt ? "Modelo de dados" : "Data model"}</a><a href="#dates">{pt ? "Datas e períodos" : "Dates & periods"}</a><a href="#revisions">{pt ? "Revisões" : "Revisions"}</a><strong>{pt ? "Referência" : "Reference"}</strong><a href={localized(locale, "/docs/api-reference")}>{pt ? "Referência da API" : "API reference"}</a><a href={localized(locale, "/docs/errors")}>{pt ? "Erros" : "Errors"}</a><a href={localized(locale, "/docs/attribution")}>{pt ? "Atribuição" : "Attribution"}</a></aside><article className="atlas-docs-content">
    <section id="quickstart"><p className="atlas-kicker">01 / {pt ? "Comece aqui" : "Start here"}</p><h2>{pt ? "Início rápido em cinco minutos" : "Five-minute quickstart"}</h2><p>{pt ? "A API é anônima, somente leitura e usa HTTPS. Encontre um ID estável e peça observações." : "The API is anonymous, read-only, and available over HTTPS. Find a stable ID, then request observations."}</p><h3>1. {pt ? "Encontre uma série" : "Find a series"}</h3><pre><code>curl --fail --silent &quot;{SITE_ORIGIN}/api/v1/indicators?q=ipca&amp;source=IBGE&quot;</code></pre><h3>2. {pt ? "Peça um período" : "Request a range"}</h3><pre><code>curl --fail --silent &quot;{SITE_ORIGIN}/api/v1/indicators/br-ipca-monthly/observations?start=2024-01-01&amp;format=json&quot;</code></pre><a className="atlas-button primary" href={localized(locale, "/playground?indicator=br-ipca-monthly")}>{pt ? "Executar no playground" : "Run in playground"}<span>↗</span></a></section>
    <section id="model"><p className="atlas-kicker">02 / {pt ? "Modelo central" : "Core model"}</p><h2>{pt ? "Série, observação e origem" : "Series, observation, and provenance"}</h2><p>{pt ? "Um indicador é uma definição curada e estável. Uma observação é o valor oficial de um período de referência." : "An indicator is a stable, curated definition. An observation is the official value for one reference period."}</p><div className="atlas-schema"><div><code>date</code><span>{pt ? "Data ISO normalizada" : "Normalized ISO date"}</span></div><div><code>period</code><span>{pt ? "Período legível" : "Human reference period"}</span></div><div><code>source_date</code><span>{pt ? "Chave original do publicador" : "Original publisher key"}</span></div><div><code>value</code><span>{pt ? "Número ou null; nunca estimado" : "Number or null; never invented"}</span></div><div><code>raw_value</code><span>{pt ? "Valor literal da fonte" : "Exact upstream value"}</span></div><div><code>status</code><span>{pt ? "Semântica explícita" : "Explicit value semantics"}</span></div></div></section>
    <section id="dates"><p className="atlas-kicker">03 / {pt ? "Semântica" : "Semantics"}</p><h2>{pt ? "Datas não são apenas rótulos" : "Dates are not just labels"}</h2><ul><li>{pt ? "Datas de requisição usam YYYY-MM-DD e são inclusivas." : "Request dates use YYYY-MM-DD and are inclusive."}</li><li>{pt ? "Séries mensais do BCB usam dia 01 como marcador do mês de referência." : "BCB monthly series use day 01 as a reference-month marker."}</li><li>{pt ? "Chaves de seis dígitos do IBGE são interpretadas pela frequência." : "IBGE six-digit keys are parsed by frequency."}</li><li>{pt ? "Trimestres móveis da PNAD se sobrepõem e não são pontos mensais." : "PNAD moving quarters overlap; they are not monthly points."}</li></ul></section>
    <section id="revisions"><p className="atlas-kicker">04 / {pt ? "Política de revisões" : "Revision policy"}</p><h2>{pt ? "A história oficial pode mudar" : "Official history can change"}</h2><p>{pt ? "PIB, ajustes sazonais e outras séries podem ser revisados. O histórico é atualizado por upsert; respostas antigas não são tratadas como imutáveis." : "GDP, seasonal adjustments, and other series can be revised. History is refreshed and upserted rather than treated as append-only."}</p><div className="docs-callout"><strong>stale: true</strong><span>{pt ? "Snapshot válido anterior, marcado com Warning 110." : "A prior valid snapshot, marked with Warning 110."}</span></div></section>
  </article></div><SiteFooter locale={locale} /></main>;
}
