import type { Category, Frequency, IndicatorDefinition } from "@/lib/domain/types";

const BCB_LICENSE = "Open Data Commons Open Database License (ODbL)";
const BCB_LICENSE_URL = "https://opendatacommons.org/licenses/odbl/1-0/";
const IBGE_LICENSE = "IBGE terms of use";
const IBGE_LICENSE_URL = "https://www.ibge.gov.br/termos-de-uso.html";

type BcbInput = Omit<IndicatorDefinition, "provider" | "sourceAgency" | "geography" | "upstream" | "sourceUrl" | "license" | "licenseUrl" | "cacheTtlSeconds" | "dateSemantics" | "transformations"> & {
  code: number;
  cacheTtlSeconds?: number;
  dateSemantics?: string;
  transformations?: string[];
};

function bcb(input: BcbInput): IndicatorDefinition {
  const { code, cacheTtlSeconds, dateSemantics, transformations, ...rest } = input;
  return {
    ...rest,
    provider: "bcb-sgs",
    sourceAgency: "BCB",
    geography: "Brazil",
    upstream: { seriesCode: code },
    sourceUrl: `https://www3.bcb.gov.br/sgspub/consultarmetadados/consultarMetadadosSeries.do?method=consultarMetadadosSeriesInternet&hdOidSerieSelecionada=${code}`,
    license: BCB_LICENSE,
    licenseUrl: BCB_LICENSE_URL,
    cacheTtlSeconds: cacheTtlSeconds ?? (rest.frequency === "daily" ? 3600 : 21600),
    dateSemantics: dateSemantics ?? (
      rest.frequency === "daily"
        ? "Official BCB observation date."
        : "Normalized to the first calendar day of the BCB reference month; source_date preserves BCB's published date label."
    ),
    transformations: transformations ?? [],
  };
}

type IbgeInput = Omit<IndicatorDefinition, "provider" | "sourceAgency" | "geography" | "upstream" | "sourceUrl" | "license" | "licenseUrl" | "cacheTtlSeconds" | "dateSemantics" | "transformations"> & {
  aggregate: number;
  variable: number;
  classification?: string;
  cacheTtlSeconds?: number;
  dateSemantics?: string;
  transformations?: string[];
};

function ibge(input: IbgeInput): IndicatorDefinition {
  const { aggregate, variable, classification, cacheTtlSeconds, dateSemantics, transformations, ...rest } = input;
  return {
    ...rest,
    provider: "ibge-aggregates",
    sourceAgency: "IBGE",
    geography: "Brazil",
    upstream: { aggregate, variable, classification },
    sourceUrl: `https://servicodados.ibge.gov.br/api/v3/agregados/${aggregate}/metadados`,
    license: IBGE_LICENSE,
    licenseUrl: IBGE_LICENSE_URL,
    cacheTtlSeconds: cacheTtlSeconds ?? 21600,
    dateSemantics: dateSemantics ?? "Normalized to the first calendar day of the official IBGE reference period; source_date preserves the original IBGE period key.",
    transformations: transformations ?? [],
  };
}

export const indicators: IndicatorDefinition[] = [
  ibge({
    id: "br-ipca-monthly",
    name: "IPCA — monthly change",
    officialName: "IPCA - Variação mensal",
    description: "Monthly change in Brazil's official broad consumer price index.",
    category: "inflation",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1979-12-01",
    aggregate: 1737,
    variable: 63,
    aliases: ["IPCA", "inflation", "inflação", "consumer prices", "63", "1737"],
    featured: true,
  }),
  ibge({
    id: "br-ipca-12m",
    name: "IPCA — 12-month change",
    officialName: "IPCA - Variação acumulada em 12 meses",
    description: "Change in the IPCA over the trailing twelve months.",
    category: "inflation",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1980-11-01",
    aggregate: 1737,
    variable: 2265,
    aliases: ["IPCA 12 months", "IPCA 12 meses", "annual inflation", "2265"],
    featured: true,
  }),
  ibge({
    id: "br-inpc-monthly",
    name: "INPC — monthly change",
    officialName: "INPC - Variação mensal",
    description: "Monthly change in the consumer price index focused on lower-income households.",
    category: "inflation",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1979-12-01",
    aggregate: 1736,
    variable: 44,
    aliases: ["INPC", "consumer prices", "inflação", "44", "1736"],
  }),
  ibge({
    id: "br-inpc-12m",
    name: "INPC — 12-month change",
    officialName: "INPC - Variação acumulada em 12 meses",
    description: "Change in the INPC over the trailing twelve months.",
    category: "inflation",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1980-11-01",
    aggregate: 1736,
    variable: 2292,
    aliases: ["INPC 12 months", "INPC 12 meses", "2292"],
  }),
  bcb({
    id: "br-selic-target",
    name: "Selic target rate",
    officialName: "Taxa de juros - Meta Selic definida pelo Copom",
    description: "Policy interest-rate target set by the Monetary Policy Committee (Copom).",
    category: "interest-rates",
    frequency: "daily",
    unit: "Percent per year",
    unitSymbol: "% p.a.",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1999-03-05",
    code: 432,
    aliases: ["Selic", "Copom", "policy rate", "taxa Selic", "432"],
    featured: true,
  }),
  bcb({
    id: "br-selic-effective",
    name: "Effective Selic rate",
    officialName: "Taxa de juros - Selic anualizada base 252",
    description: "Annualized effective overnight Selic rate on a 252-business-day basis.",
    category: "interest-rates",
    frequency: "daily",
    unit: "Percent per year",
    unitSymbol: "% p.a.",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1986-06-04",
    code: 1178,
    aliases: ["effective Selic", "Selic efetiva", "overnight rate", "1178"],
  }),
  bcb({
    id: "br-selic-monthly",
    name: "Selic accumulated in month",
    officialName: "Taxa de juros - Selic acumulada no mês",
    description: "Cumulative effective Selic rate during each calendar month.",
    category: "interest-rates",
    frequency: "monthly",
    unit: "Percent per month",
    unitSymbol: "% p.m.",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1986-07-01",
    code: 4390,
    aliases: ["Selic monthly", "Selic mensal", "4390"],
  }),
  bcb({
    id: "br-usd-brl",
    name: "US dollar / Brazilian real",
    officialName: "Taxa de câmbio - Livre - Dólar americano (venda) - diário",
    description: "Daily Brazilian reais per US dollar selling exchange rate.",
    category: "currencies",
    frequency: "daily",
    unit: "Brazilian reais per US dollar",
    unitSymbol: "BRL/USD",
    decimals: 4,
    seasonalAdjustment: false,
    startDate: "1984-11-28",
    code: 1,
    aliases: ["USD BRL", "dólar", "dollar", "PTAX", "câmbio", "1"],
    featured: true,
  }),
  bcb({
    id: "br-ibc-br",
    name: "IBC-Br economic activity index",
    officialName: "Índice de Atividade Econômica do Banco Central - IBC-Br",
    description: "Monthly coincident indicator of nationwide economic activity.",
    category: "activity",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "index",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2003-01-01",
    code: 24363,
    aliases: ["IBC-Br", "economic activity", "atividade econômica", "24363"],
    featured: true,
  }),
  bcb({
    id: "br-ibc-br-sa",
    name: "IBC-Br — seasonally adjusted",
    officialName: "Índice de Atividade Econômica do Banco Central - IBC-Br com ajuste sazonal",
    description: "Seasonally adjusted monthly index of nationwide economic activity.",
    category: "activity",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "index",
    decimals: 2,
    seasonalAdjustment: true,
    startDate: "2003-01-01",
    code: 24364,
    aliases: ["IBC-Br SA", "atividade econômica dessazonalizada", "24364"],
  }),
  ibge({
    id: "br-gdp-real-yoy",
    name: "Real GDP — year-on-year",
    officialName: "PIB a preços de mercado - Taxa acumulada em quatro trimestres",
    description: "Real gross domestic product growth relative to the same period of the prior year.",
    category: "activity",
    frequency: "quarterly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "1996-01-01",
    aggregate: 5932,
    variable: 6561,
    classification: "11255[90707]",
    aliases: ["GDP", "PIB", "economic growth", "crescimento", "6561"],
    featured: true,
  }),
  ibge({
    id: "br-gdp-real-qoq-sa",
    name: "Real GDP — quarter-on-quarter",
    officialName: "PIB a preços de mercado - Variação em relação ao trimestre anterior",
    description: "Seasonally adjusted real GDP change from the previous quarter.",
    category: "activity",
    frequency: "quarterly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "1996-01-01",
    aggregate: 5932,
    variable: 6564,
    classification: "11255[90707]",
    aliases: ["GDP QoQ", "PIB trimestral", "quarterly GDP", "6564"],
  }),
  ibge({
    id: "br-industrial-production-sa",
    name: "Industrial production index",
    officialName: "Produção física industrial - Índice com ajuste sazonal",
    description: "Seasonally adjusted index of industrial physical production.",
    category: "activity",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "2022=100",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "2002-01-01",
    aggregate: 8888,
    variable: 12607,
    classification: "544[129314]",
    aliases: ["industrial production", "produção industrial", "PIM-PF", "12607"],
  }),
  ibge({
    id: "br-industrial-production-mom",
    name: "Industrial production — monthly change",
    officialName: "Produção física industrial - Variação mês/mês anterior com ajuste sazonal",
    description: "Seasonally adjusted monthly change in industrial production.",
    category: "activity",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "2002-02-01",
    aggregate: 8888,
    variable: 11601,
    classification: "544[129314]",
    aliases: ["industry MoM", "produção industrial mensal", "11601"],
  }),
  ibge({
    id: "br-retail-sales-sa",
    name: "Retail sales volume index",
    officialName: "Volume de vendas no comércio varejista - Índice com ajuste sazonal",
    description: "Seasonally adjusted volume index for core retail sales.",
    category: "activity",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "2022=100",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "2000-01-01",
    aggregate: 8880,
    variable: 7170,
    classification: "11046[56734]",
    aliases: ["retail sales", "vendas varejo", "PMC", "7170"],
  }),
  ibge({
    id: "br-retail-sales-mom",
    name: "Retail sales — monthly change",
    officialName: "Volume de vendas no comércio varejista - Variação mês/mês anterior",
    description: "Seasonally adjusted monthly change in core retail sales volume.",
    category: "activity",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "2000-02-01",
    aggregate: 8880,
    variable: 11708,
    classification: "11046[56734]",
    aliases: ["retail MoM", "varejo mensal", "11708"],
  }),
  ibge({
    id: "br-services-volume-sa",
    name: "Services volume index",
    officialName: "Volume de serviços - Índice com ajuste sazonal",
    description: "Seasonally adjusted index of service-sector volume.",
    category: "activity",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "2022=100",
    decimals: 1,
    seasonalAdjustment: true,
    startDate: "2011-01-01",
    aggregate: 5906,
    variable: 7168,
    classification: "11046[56726]",
    aliases: ["services index", "volume de serviços", "PMS", "7168"],
  }),
  ibge({
    id: "br-unemployment-rate",
    name: "Unemployment rate",
    officialName: "Taxa de desocupação das pessoas de 14 anos ou mais de idade",
    description: "Unemployment rate for people aged 14 or older, measured over a moving quarter.",
    category: "labor",
    frequency: "monthly",
    unit: "Percent of labor force",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "2012-03-01",
    aggregate: 6381,
    variable: 4099,
    aliases: ["unemployment", "desemprego", "desocupação", "PNAD Contínua", "4099"],
    featured: true,
    dateSemantics: "Final month of the official three-month moving reference quarter.",
    notes: "Each observation describes a moving quarter ending in the displayed month.",
  }),
  ibge({
    id: "br-real-earnings",
    name: "Real usual monthly earnings",
    officialName: "Rendimento médio real habitualmente recebido",
    description: "Average real usual monthly earnings of employed people aged 14 or older.",
    category: "labor",
    frequency: "monthly",
    unit: "Brazilian reais",
    unitSymbol: "R$",
    decimals: 0,
    seasonalAdjustment: false,
    startDate: "2012-03-01",
    aggregate: 6390,
    variable: 5933,
    aliases: ["earnings", "wages", "rendimento real", "salário", "5933"],
    dateSemantics: "Final month of the official three-month moving reference quarter.",
  }),
  ibge({
    id: "br-informality-rate",
    name: "Informality rate",
    officialName: "Taxa de informalidade das pessoas ocupadas",
    description: "Share of employed people working in informal arrangements.",
    category: "labor",
    frequency: "monthly",
    unit: "Percent of employed population",
    unitSymbol: "%",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "2015-12-01",
    aggregate: 8513,
    variable: 12466,
    aliases: ["informality", "informal work", "informalidade", "12466"],
    dateSemantics: "Final month of the official three-month moving reference quarter.",
  }),
  bcb({
    id: "br-credit-gdp",
    name: "Credit portfolio to GDP",
    officialName: "Saldo da carteira de crédito em relação ao PIB",
    description: "Outstanding credit portfolio as a share of gross domestic product.",
    category: "credit",
    frequency: "monthly",
    unit: "Percent of GDP",
    unitSymbol: "% GDP",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2011-03-01",
    code: 20622,
    aliases: ["credit GDP", "crédito PIB", "20622"],
    featured: true,
  }),
  bcb({
    id: "br-credit-interest-rate",
    name: "Average credit interest rate",
    officialName: "Taxa média de juros das operações de crédito - Total",
    description: "Average annual interest rate across credit operations in the financial system.",
    category: "credit",
    frequency: "monthly",
    unit: "Percent per year",
    unitSymbol: "% p.a.",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2011-03-01",
    code: 20714,
    aliases: ["lending rate", "juros crédito", "20714"],
  }),
  bcb({
    id: "br-credit-delinquency",
    name: "Credit delinquency rate",
    officialName: "Inadimplência da carteira de crédito - Total",
    description: "Share of the total credit portfolio with payments more than 90 days overdue.",
    category: "credit",
    frequency: "monthly",
    unit: "Percent",
    unitSymbol: "%",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2011-03-01",
    code: 21082,
    aliases: ["delinquency", "default rate", "inadimplência", "21082"],
  }),
  bcb({
    id: "br-net-public-debt-gdp",
    name: "Public-sector net debt",
    officialName: "Dívida Líquida do Setor Público (% PIB) - Total",
    description: "Net debt of Brazil's consolidated public sector as a share of GDP.",
    category: "fiscal",
    frequency: "monthly",
    unit: "Percent of GDP",
    unitSymbol: "% GDP",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2001-12-01",
    code: 4513,
    aliases: ["net debt", "DLSP", "dívida líquida", "4513"],
  }),
  bcb({
    id: "br-gross-government-debt-gdp",
    name: "General-government gross debt",
    officialName: "Dívida bruta do governo geral (% PIB) - Metodologia utilizada a partir de 2008",
    description: "Gross debt of federal, state, and municipal governments under the post-2008 methodology.",
    category: "fiscal",
    frequency: "monthly",
    unit: "Percent of GDP",
    unitSymbol: "% GDP",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2006-12-01",
    code: 13762,
    aliases: ["gross debt", "DBGG", "dívida bruta", "13762"],
    featured: true,
  }),
  bcb({
    id: "br-primary-balance-12m-gdp",
    name: "Public-sector primary balance",
    officialName: "NFSP sem desvalorização cambial (% PIB) - Resultado primário - Total",
    description: "Twelve-month accumulated primary borrowing requirement of the consolidated public sector.",
    category: "fiscal",
    frequency: "monthly",
    unit: "Percent of GDP",
    unitSymbol: "% GDP",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2002-11-01",
    code: 5793,
    aliases: ["primary balance", "resultado primário", "NFSP", "5793"],
    notes: "BCB's NFSP convention records borrowing requirements with their published sign. Values are not sign-inverted.",
  }),
  bcb({
    id: "br-nominal-balance-12m-gdp",
    name: "Public-sector nominal balance",
    officialName: "NFSP sem desvalorização cambial (% PIB) - Resultado nominal - Total",
    description: "Twelve-month accumulated nominal borrowing requirement of the consolidated public sector.",
    category: "fiscal",
    frequency: "monthly",
    unit: "Percent of GDP",
    unitSymbol: "% GDP",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "2002-11-01",
    code: 5727,
    aliases: ["nominal balance", "resultado nominal", "NFSP", "5727"],
    notes: "BCB's NFSP convention records borrowing requirements with their published sign. Values are not sign-inverted.",
  }),
  bcb({
    id: "br-current-account",
    name: "Current account balance",
    officialName: "Transações correntes - mensal - saldo",
    description: "Monthly balance on Brazil's current account in the balance of payments.",
    category: "external",
    frequency: "monthly",
    unit: "US dollars, millions",
    unitSymbol: "US$ mn",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "1995-01-01",
    code: 22701,
    aliases: ["current account", "conta corrente", "transações correntes", "22701"],
    featured: true,
  }),
  bcb({
    id: "br-goods-balance",
    name: "Balance-of-payments goods balance",
    officialName: "Balanço de pagamentos - Balança comercial - saldo",
    description: "Monthly goods balance recorded in Brazil's balance of payments.",
    category: "external",
    frequency: "monthly",
    unit: "US dollars, millions",
    unitSymbol: "US$ mn",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "1995-01-01",
    code: 22707,
    aliases: ["trade balance", "goods balance", "balança comercial", "22707"],
  }),
  bcb({
    id: "br-fdi-net",
    name: "Direct investment in Brazil",
    officialName: "Investimento direto no país - líquido",
    description: "Monthly net direct investment flows into Brazil.",
    category: "external",
    frequency: "monthly",
    unit: "US dollars, millions",
    unitSymbol: "US$ mn",
    decimals: 1,
    seasonalAdjustment: false,
    startDate: "1995-01-01",
    code: 22885,
    aliases: ["FDI", "investimento direto", "IDP", "22885"],
  }),
  bcb({
    id: "br-international-reserves",
    name: "International reserves",
    officialName: "Reservas internacionais - Conceito liquidez - Total - diária",
    description: "Brazil's total international reserves under the liquidity concept.",
    category: "external",
    frequency: "daily",
    unit: "US dollars, millions",
    unitSymbol: "US$ mn",
    decimals: 0,
    seasonalAdjustment: false,
    startDate: "2000-01-03",
    code: 13982,
    aliases: ["reserves", "reservas internacionais", "foreign reserves", "13982"],
  }),
  bcb({
    id: "br-icb-br",
    name: "Brazil commodity price index",
    officialName: "Índice de Commodities Brasil - IC-Br",
    description: "Commodity price index weighted to reflect their relevance to Brazilian inflation.",
    category: "markets",
    frequency: "monthly",
    unit: "Index",
    unitSymbol: "index",
    decimals: 2,
    seasonalAdjustment: false,
    startDate: "1998-01-01",
    code: 27574,
    aliases: ["IC-Br", "commodities", "commodity index", "27574"],
  }),
];

export const categoryLabels: Record<Category, string> = {
  inflation: "Inflation",
  "interest-rates": "Interest rates",
  currencies: "Currencies",
  activity: "Economic activity",
  labor: "Labor",
  credit: "Credit",
  fiscal: "Fiscal",
  external: "External sector",
  markets: "Markets",
};

export const categoryDescriptions: Record<Category, string> = {
  inflation: "Consumer prices and inflation dynamics",
  "interest-rates": "Monetary policy and market interest rates",
  currencies: "Official foreign-exchange reference rates",
  activity: "GDP, production, retail, services, and monthly activity",
  labor: "Employment, earnings, and labor-market structure",
  credit: "Credit volumes, pricing, and delinquency",
  fiscal: "Government debt and fiscal balances",
  external: "Balance of payments, investment flows, and reserves",
  markets: "Market-relevant price and commodity indicators",
};

export function getIndicator(id: string) {
  return indicators.find((indicator) => indicator.id === id);
}

export function searchIndicators(query: string) {
  const normalized = query.trim().toLocaleLowerCase("en");
  if (!normalized) return indicators;
  return indicators.filter((indicator) =>
    [
      indicator.id,
      indicator.name,
      indicator.officialName,
      indicator.description,
      categoryLabels[indicator.category],
      indicator.sourceAgency,
      ...indicator.aliases,
    ]
      .join(" ")
      .toLocaleLowerCase("en")
      .includes(normalized),
  );
}

export function indicatorsByCategory(category: Category) {
  return indicators.filter((indicator) => indicator.category === category);
}

export const catalogSummary = {
  indicators: indicators.length,
  categories: new Set(indicators.map((indicator) => indicator.category)).size,
  sources: new Set(indicators.map((indicator) => indicator.sourceAgency)).size,
};

export function frequencies(): Frequency[] {
  return ["daily", "monthly", "quarterly", "annual"];
}
