import { notFound } from "next/navigation";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";
import { categoryLabels, indicators } from "@/lib/catalog/indicators";
import { sources } from "@/lib/catalog/sources";
import { isLocale, localized } from "@/lib/i18n";

export default async function SourcesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: value } = await params; if (!isLocale(value)) notFound(); const locale = value; const pt = locale === "pt-br";
  return <main className="atlas-page"><SiteHeader locale={locale} /><section className="atlas-page-hero atlas-shell"><p className="atlas-kicker">06 / Provenance</p><div><h1>{pt ? "Saiba de onde cada valor veio." : "Know where every value came from."}</h1><p>{pt ? "Normalizamos o acesso, não a autoria. Publicador, identificador, licença e momento de recuperação permanecem visíveis." : "We normalize access, not authorship. Publisher, identifier, license, and retrieval time remain visible."}</p></div></section><section className="atlas-sources atlas-shell">{sources.map((source, index) => { const sourceIndicators = indicators.filter((indicator) => indicator.sourceAgency === source.shortName); const categories = [...new Set(sourceIndicators.map((indicator) => indicator.category))]; return <article id={source.id} key={source.id}><div className="source-number">0{index + 1}</div><div><p className="atlas-kicker">{pt ? "Publicador oficial" : "Official publisher"}</p><h2>{source.name}</h2><p>{source.description}</p><div className="source-coordinates"><span>{sourceIndicators.length}<small>{pt ? "séries conectadas" : "connected series"}</small></span><span>{categories.length}<small>{pt ? "temas" : "topics"}</small></span><span>{source.shortName}<small>{pt ? "identificador" : "coordinate"}</small></span></div></div><div className="source-map"><span>{categories.map((category) => categoryLabels[category]).join(" · ")}</span>{sourceIndicators.slice(0, 7).map((indicator) => <a href={localized(locale, `/indicators/${indicator.id}`)} key={indicator.id}><b>{indicator.name}</b><small>{indicator.id} · {indicator.unitSymbol}</small></a>)}<a className="source-all" href={localized(locale, `/catalog?source=${source.shortName}`)}>{pt ? "Ver todas as séries" : "View every series"} →</a></div><footer><span>{source.attribution}</span><a href={source.catalogUrl} target="_blank" rel="noreferrer">{pt ? "Catálogo oficial" : "Official catalog"} ↗</a></footer></article>; })}</section><SiteFooter locale={locale} /></main>;
}

